----------------------------------------------------------------------------------------------------
-- dinv migration module
--
-- Migrates data from old aard_inventory (plugin ID 88c86ea252fc1918556df9fe) serialized
-- Lua state files into dinv's SQLite database.
--
-- The old state files are never modified. Migration replaces the current dinv database
-- (a backup is created first). The migration is atomic: if any step fails, the database
-- is rolled back and the backup is restored.
--
-- Old state files are loaded using Lua's loadstring(). This is safe because the files
-- were generated by the user's own plugin installation and contain only Lua table
-- assignments. A line-by-line parser would be fragile and would essentially re-implement
-- a subset of the Lua parser; loadstring is the most reliable approach.
--
-- Functions:
--   inv.migrate.getOldDir()       -- Get path to old aard_inventory state directory
--   inv.migrate.detect()          -- Detect old state files, return summary
--   inv.migrate.execute()         -- Run the migration
--   inv.migrate.loadStateFile()   -- Load a single .state file via loadstring
----------------------------------------------------------------------------------------------------

inv.migrate = {}

-- Old aard_inventory plugin ID
local oldPluginId = "88c86ea252fc1918556df9fe"

-- State files we can migrate, in order of processing.  Order matters: things that
-- reference an objId must come after items so any later cross-checks succeed.
-- Equip bonuses are deliberately not migrated -- they are a deterministic cache
-- of (levelBonus - spellBonus) that inv.statBonus.get recomputes on demand;
-- v3.0097 stopped persisting them, so importing old equip rows would be wasted
-- work (the next save's DELETE FROM stat_bonuses wipes them anyway).
local stateFiles = {
  { file = "inv-items.state",          desc = "Items",         root = "inv.items.table" },
  { file = "inv-priorities.state",     desc = "Priorities",    root = "inv.priority.table" },
  { file = "inv-set.state",            desc = "Sets",          root = "inv.set.table" },
  { file = "inv-snapshot.state",       desc = "Snapshots",     root = "inv.snapshot.table" },
  { file = "inv-consume.state",        desc = "Consumables",   root = "inv.consume.table" },
  { file = "inv-cache-custom.state",   desc = "Custom cache",  root = "inv.cache.custom.table" },
  { file = "inv-cache-frequent.state", desc = "Frequent cache",root = "inv.cache.frequent.table" },
  { file = "inv-cache-recent.state",   desc = "Recent cache",  root = "inv.cache.recent.table" },
  { file = "inv-stats-spells.state",   desc = "Spell bonuses", root = "inv.statBonus.spellBonus" },
  { file = "inv-config.state",         desc = "Config",        root = "inv.config.table" },
}


----------------------------------------------------------------------------------------------------
-- Error logging
--
-- loadStateFile failures are not fatal (we commit whatever else migrated successfully) so the
-- original error message from loadstring/pcall is easy to miss in the chat window. Mirror it
-- to a file next to dinv.db so the user can inspect exactly why a given state file did not load.
----------------------------------------------------------------------------------------------------

local function getErrorLogPath()
  return dinv_db.getDir() .. "migrate-errors.log"
end

local function writeLoadError(filePath, errMsg)
  local logPath = getErrorLogPath()
  local f = io.open(logPath, "a")
  if not f then
    return  -- best-effort; don't block migration if the log can't be written
  end
  f:write(string.format("[%s] %s\n  %s\n\n",
                        os.date("%Y-%m-%d %H:%M:%S"),
                        filePath or "?",
                        errMsg or "unknown error"))
  f:close()
end


----------------------------------------------------------------------------------------------------
-- Path helpers
----------------------------------------------------------------------------------------------------

-- Returns the base state directory (without plugin-specific suffix).
-- Derived from pluginStatePath by stripping "dinv-{currentPluginId}".
function inv.migrate.getStateBase()
  local suffix = "dinv-" .. pluginId
  local pos = pluginStatePath:find(suffix, 1, true)
  if not pos then return nil end
  return pluginStatePath:sub(1, pos - 1)
end


-- Returns the path to the old aard_inventory state directory for the current character.
function inv.migrate.getOldDir()
  local base = inv.migrate.getStateBase()
  if not base then return nil end

  local charName = dbot.gmcp.getName()
  if not charName then return nil end

  return base .. "dinv-" .. oldPluginId .. "\\" .. charName .. "\\current\\"
end


----------------------------------------------------------------------------------------------------
-- State file loader
----------------------------------------------------------------------------------------------------

-- Load a single .state file using loadstring.
-- Returns the root table on success, or nil and an error message on failure.
--
-- The file format is:
--   Line 1: version number (always "1")
--   Line 2: SHA1 hash (integrity check, not validated during migration)
--   Line 3+: Lua table assignment code
--
-- We skip lines 1-2 and execute the rest. The code assigns into global variables
-- (e.g., inv.items.table = {}; inv.items.table[id].field = value).
-- We set up a sandboxed environment with the necessary root tables pre-declared,
-- then extract the populated table after execution.
function inv.migrate.loadStateFile(filePath, rootPath)
  local f = io.open(filePath, "r")
  if not f then
    return nil, "Cannot open file: " .. filePath
  end

  local content = f:read("*a")
  f:close()

  if not content or content == "" then
    return nil, "File is empty: " .. filePath
  end

  -- Skip lines 1 (version) and 2 (hash)
  local lineNum = 0
  local codeStart = nil
  for i = 1, #content do
    if content:sub(i, i) == "\n" then
      lineNum = lineNum + 1
      if lineNum == 2 then
        codeStart = i + 1
        break
      end
    end
  end

  if not codeStart then
    return nil, "File has fewer than 3 lines: " .. filePath
  end

  local code = content:sub(codeStart)

  -- Build a sandbox environment with the root path pre-declared.
  -- For "inv.items.table", we need: env.inv = { items = { table = {} } }
  -- The loadstring code will then populate env.inv.items.table.
  local env = {}

  -- Parse the root path (e.g., "inv.items.table") into nested tables
  local parts = {}
  for part in rootPath:gmatch("[^%.]+") do
    table.insert(parts, part)
  end

  -- Create nested structure
  local current = env
  for i = 1, #parts do
    current[parts[i]] = {}
    current = current[parts[i]]
  end

  -- Allow access to standard globals needed by the serialized code
  setmetatable(env, { __index = _G })

  -- Load and execute the code in the sandbox
  local fn, err = loadstring(code)
  if not fn then
    return nil, "Failed to parse state file: " .. (err or "unknown error")
  end

  setfenv(fn, env)
  local ok, execErr = pcall(fn)
  if not ok then
    return nil, "Failed to execute state file: " .. (execErr or "unknown error")
  end

  -- Extract the root table from the environment
  current = env
  for i = 1, #parts do
    current = current[parts[i]]
    if not current then
      return nil, "Root table " .. rootPath .. " was not populated"
    end
  end

  return current
end


----------------------------------------------------------------------------------------------------
-- Detection
----------------------------------------------------------------------------------------------------

-- Detect old state files and return a summary table.
-- Returns { found = true/false, dir = path, files = { {file, desc, exists, path}, ... } }
function inv.migrate.detect()
  local result = { found = false, dir = nil, files = {} }

  local oldDir = inv.migrate.getOldDir()
  if not oldDir then
    return result
  end

  result.dir = oldDir

  if not dbot.fileExists(oldDir) then
    return result
  end

  for _, sf in ipairs(stateFiles) do
    local path = oldDir .. sf.file
    local exists = dbot.fileExists(path)
    table.insert(result.files, {
      file   = sf.file,
      desc   = sf.desc,
      exists = exists,
      path   = path,
      root   = sf.root,
    })
    if exists then
      result.found = true
    end
  end

  return result
end


----------------------------------------------------------------------------------------------------
-- Migration: Items
----------------------------------------------------------------------------------------------------

local function migrateItems(data)
  local db = dinv_db.handle
  local count = 0

  for objId, entry in pairs(data) do
    local query = dinv_db.buildItemInsert("items", objId, entry)
    db:exec(query)
    if dinv_db.dbcheck(db:errcode(), db:errmsg(), query) then
      return nil, "Failed to insert item " .. tostring(objId)
    end
    count = count + 1
  end

  return count
end


----------------------------------------------------------------------------------------------------
-- Migration: Priorities
----------------------------------------------------------------------------------------------------

local function migratePriorities(data)
  local db = dinv_db.handle
  local count = 0

  for priorityName, blocks in pairs(data) do
    local query = string.format("INSERT INTO priorities (name) VALUES (%s)",
                                dinv_db.fixsql(priorityName))
    db:exec(query)
    if dinv_db.dbcheck(db:errcode(), db:errmsg(), query) then
      return nil, "Failed to insert priority " .. priorityName
    end

    local priorityId = db:last_insert_rowid()

    for blockIdx, block in ipairs(blocks) do
      local columns = "priority_id, block_index, min_level, max_level"
      local values = string.format("%d, %d, %d, %d",
                                    priorityId, blockIdx,
                                    block.minLevel or 1, block.maxLevel or 291)

      if block.priorities then
        for luaKey, weight in pairs(block.priorities) do
          local sqlCol = inv.priority.luaToSql[luaKey]
          if sqlCol and weight ~= 0 then
            columns = columns .. ", " .. sqlCol
            values = values .. ", " .. tostring(weight)
          end
        end
      end

      query = string.format("INSERT INTO priority_blocks (%s) VALUES (%s)", columns, values)
      db:exec(query)
      if dinv_db.dbcheck(db:errcode(), db:errmsg(), query) then
        return nil, "Failed to insert priority block for " .. priorityName
      end
    end

    count = count + 1
  end

  return count
end


----------------------------------------------------------------------------------------------------
-- Migration: Sets
----------------------------------------------------------------------------------------------------

local function migrateSets(data)
  local db = dinv_db.handle
  local count = 0

  for priorityName, levels in pairs(data) do
    for level, equipSet in pairs(levels) do
      for wearLoc, itemData in pairs(equipSet) do
        local query = string.format(
          "INSERT INTO sets (priority_name, level, wear_loc, obj_id, score) VALUES (%s, %d, %s, %s, %s)",
          dinv_db.fixsql(priorityName),
          level,
          dinv_db.fixsql(wearLoc),
          dinv_db.fixnum(itemData.id),
          dinv_db.fixnum(itemData.score))
        db:exec(query)
        if dinv_db.dbcheck(db:errcode(), db:errmsg(), query) then
          return nil, "Failed to insert set " .. priorityName .. "[" .. level .. "]"
        end
        count = count + 1
      end
    end
  end

  return count
end


----------------------------------------------------------------------------------------------------
-- Migration: Snapshots
----------------------------------------------------------------------------------------------------

local function migrateSnapshots(data)
  local db = dinv_db.handle
  local count = 0

  for snapName, equipSet in pairs(data) do
    for wearLoc, itemData in pairs(equipSet) do
      local query = string.format(
        "INSERT INTO snapshots (snapshot_name, wear_loc, obj_id, score) VALUES (%s, %s, %s, %s)",
        dinv_db.fixsql(snapName),
        dinv_db.fixsql(wearLoc),
        dinv_db.fixnum(itemData.id),
        dinv_db.fixnum(itemData.score))
      db:exec(query)
      if dinv_db.dbcheck(db:errcode(), db:errmsg(), query) then
        return nil, "Failed to insert snapshot " .. snapName .. "[" .. wearLoc .. "]"
      end
      count = count + 1
    end
  end

  return count
end


----------------------------------------------------------------------------------------------------
-- Migration: Consumables
----------------------------------------------------------------------------------------------------

local function migrateConsumables(data)
  local db = dinv_db.handle
  local count = 0

  for typeName, items in pairs(data) do
    for _, item in ipairs(items) do
      local query = string.format(
        "INSERT INTO consumables (type_name, level, name, room, full_name) VALUES (%s, %s, %s, %s, %s)",
        dinv_db.fixsql(typeName),
        dinv_db.fixnum(item.level),
        dinv_db.fixsql(item.name),
        dinv_db.fixsql(item.room),
        dinv_db.fixsql(item.fullName))
      db:exec(query)
      if dinv_db.dbcheck(db:errcode(), db:errmsg(), query) then
        return nil, "Failed to insert consumable " .. (item.name or "?")
      end
      count = count + 1
    end
  end

  return count
end


----------------------------------------------------------------------------------------------------
-- Migration: Custom cache
--
-- Holds user-set keywords (`dinv key`) and organize queries (`dinv organize`) keyed by objId.
-- This is the most painful cache to lose during migration because the data is manually
-- entered by the user, so it predates v3.0086 by a long way -- the omission was a real gap
-- for users coming over from aard_inventory.
----------------------------------------------------------------------------------------------------

local function migrateCacheCustom(data)
  local db = dinv_db.handle
  local count = 0

  if not data or not data.entries then return 0 end

  for objId, cacheRec in pairs(data.entries) do
    local entry = cacheRec and cacheRec.entry
    if entry then
      local query = string.format(
        "INSERT INTO cache_custom (obj_id, keywords, organize) VALUES (%s, %s, %s)",
        dinv_db.fixnum(objId),
        dinv_db.fixsql(entry.keywords),
        dinv_db.fixsql(entry.organize))
      db:exec(query)
      if dinv_db.dbcheck(db:errcode(), db:errmsg(), query) then
        return nil, "Failed to insert cache_custom row " .. tostring(objId)
      end
      count = count + 1
    end
  end

  return count
end


----------------------------------------------------------------------------------------------------
-- Migration: Frequent cache
--
-- Templates for frequently-acquired items (potions, pills, scrolls, etc.), keyed by item name
-- with commas stripped (aard_inventory convention).  Each entry is a full item record that
-- inv.items.trigger.itemDataStats clones onto a new objId when the matching item is later
-- acquired.  v3.0085's SQL fallback partially compensates if this is empty, but a migrating
-- user benefits from a hot start.
----------------------------------------------------------------------------------------------------

local function migrateCacheFrequent(data)
  local db = dinv_db.handle
  local count = 0

  if not data or not data.entries then return 0 end

  for cacheKey, cacheRec in pairs(data.entries) do
    local entry = cacheRec and cacheRec.entry
    if entry then
      local query = dinv_db.buildItemRowInsert(
        "cache_frequent", "cache_key", dinv_db.fixsql(cacheKey), entry)
      db:exec(query)
      if dinv_db.dbcheck(db:errcode(), db:errmsg(), query) then
        return nil, "Failed to insert cache_frequent row " .. tostring(cacheKey)
      end
      count = count + 1
    end
  end

  return count
end


----------------------------------------------------------------------------------------------------
-- Migration: Recent cache
--
-- Snapshots of recently-removed items, keyed by their original objId.  Lower-impact than the
-- other two caches (entries are transient and re-populate naturally during play) but migrating
-- it preserves continuity for items just dropped before the user ran the migration.
----------------------------------------------------------------------------------------------------

local function migrateCacheRecent(data)
  local db = dinv_db.handle
  local count = 0

  if not data or not data.entries then return 0 end

  for objId, cacheRec in pairs(data.entries) do
    local entry = cacheRec and cacheRec.entry
    if entry then
      local query = dinv_db.buildItemInsert("cache_recent", objId, entry)
      db:exec(query)
      if dinv_db.dbcheck(db:errcode(), db:errmsg(), query) then
        return nil, "Failed to insert cache_recent row " .. tostring(objId)
      end
      count = count + 1
    end
  end

  return count
end


----------------------------------------------------------------------------------------------------
-- Migration: Stat bonuses (spells)
----------------------------------------------------------------------------------------------------

local function migrateSpellBonuses(data)
  local db = dinv_db.handle
  local count = 0
  local stats = { "int", "wis", "luck", "str", "dex", "con" }

  for level, levelData in pairs(data) do
    for _, stat in ipairs(stats) do
      local aveVal = (levelData.ave and levelData.ave[stat]) or nil
      local maxVal = (levelData.max and levelData.max[stat]) or nil
      if aveVal or maxVal then
        local query = string.format(
          "INSERT INTO stat_bonuses (bonus_type, level, stat_name, ave_val, max_val) VALUES ('spell', %d, %s, %s, %s)",
          level, dinv_db.fixsql(stat), dinv_db.fixnum(aveVal), dinv_db.fixnum(maxVal))
        db:exec(query)
        if dinv_db.dbcheck(db:errcode(), db:errmsg(), query) then
          return nil, "Failed to insert spell bonus"
        end
        count = count + 1
      end
    end
  end

  return count
end


----------------------------------------------------------------------------------------------------
-- Migration: Config
----------------------------------------------------------------------------------------------------

-- Config keys to migrate from old format. Maps old field name to new config key.
-- Only behavioral settings are migrated; format versions are not (they are meaningless
-- in the new system).
local configKeyMap = {
  isPromptEnabled = "config.isPromptEnabled",
  isBuildExecuted = "config.isBuildExecuted",
  doIgnoreKeyring = "config.doIgnoreKeyring",
  isRegenEnabled  = "config.isRegenEnabled",
  regenOrigObjId  = "config.regenOrigObjId",
  regenNewObjId   = "config.regenNewObjId",
  refreshPeriod   = "config.refreshPeriod",
  refreshEagerSec = "config.refreshEagerSec",
}

local function migrateConfig(data)
  local db = dinv_db.handle
  local count = 0

  for oldKey, newKey in pairs(configKeyMap) do
    local val = data[oldKey]
    if val ~= nil then
      local query = string.format(
        "INSERT OR REPLACE INTO config (key, value) VALUES (%s, %s)",
        dinv_db.fixsql(newKey), dinv_db.fixsql(tostring(val)))
      db:exec(query)
      if dinv_db.dbcheck(db:errcode(), db:errmsg(), query) then
        return nil, "Failed to insert config key " .. newKey
      end
      count = count + 1
    end
  end

  return count
end


----------------------------------------------------------------------------------------------------
-- Validation
----------------------------------------------------------------------------------------------------

local function validateCount(tableName, expected)
  local db = dinv_db.handle
  local actual = 0
  for row in db:nrows("SELECT COUNT(*) as cnt FROM " .. tableName) do
    actual = row.cnt
  end
  return actual, (actual == expected)
end


----------------------------------------------------------------------------------------------------
-- Main migration execution
----------------------------------------------------------------------------------------------------

function inv.migrate.execute()
  local detection = inv.migrate.detect()

  if not detection.found then
    dbot.info("No old aard_inventory state files found. Nothing to migrate.")
    return DRL_RET_MISSING_ENTRY
  end

  -- Create a backup of the current database before we nuke it
  dbot.info("Creating backup of current database before migration...")
  local backupRetval = dbot.backup.create("pre-migrate", nil)
  if backupRetval ~= DRL_RET_SUCCESS and backupRetval ~= DRL_RET_UNINITIALIZED then
    dbot.info("Warning: Could not create backup (return code: " ..
              dbot.retval.getString(backupRetval) .. ")")
    dbot.info("Proceeding with migration anyway...")
  end

  -- Close the database, delete it, and reopen (fresh schema)
  local dbPath = dinv_db.getPath()
  dinv_db.close()

  os.remove(dbPath)

  if not dinv_db.open() then
    dbot.error("Failed to reopen database after deletion. Migration aborted.")
    return DRL_RET_INTERNAL_ERROR
  end

  -- Run migration inside a single transaction
  local results = {}
  local migrationFailed = false
  local anyLoadFailed = false
  local failureMsg = nil

  local retval = dinv_db.transaction(function()

    -- Migrate each state file that exists
    for _, fileInfo in ipairs(detection.files) do
      if fileInfo.exists then
        dbot.info("Loading " .. fileInfo.desc .. " from " .. fileInfo.file .. "...")
        local data, loadErr = inv.migrate.loadStateFile(fileInfo.path, fileInfo.root)

        if not data then
          dbot.warn("Failed to load " .. fileInfo.desc .. ": " .. (loadErr or "unknown"))
          table.insert(results, { desc = fileInfo.desc, status = "FAILED", detail = loadErr })
          writeLoadError(fileInfo.path, loadErr)
          anyLoadFailed = true

        else
          local count, migrateErr

          if fileInfo.file == "inv-items.state" then
            count, migrateErr = migrateItems(data)
          elseif fileInfo.file == "inv-priorities.state" then
            count, migrateErr = migratePriorities(data)
          elseif fileInfo.file == "inv-set.state" then
            count, migrateErr = migrateSets(data)
          elseif fileInfo.file == "inv-snapshot.state" then
            count, migrateErr = migrateSnapshots(data)
          elseif fileInfo.file == "inv-consume.state" then
            count, migrateErr = migrateConsumables(data)
          elseif fileInfo.file == "inv-cache-custom.state" then
            count, migrateErr = migrateCacheCustom(data)
          elseif fileInfo.file == "inv-cache-frequent.state" then
            count, migrateErr = migrateCacheFrequent(data)
          elseif fileInfo.file == "inv-cache-recent.state" then
            count, migrateErr = migrateCacheRecent(data)
          elseif fileInfo.file == "inv-stats-spells.state" then
            count, migrateErr = migrateSpellBonuses(data)
          elseif fileInfo.file == "inv-config.state" then
            count, migrateErr = migrateConfig(data)
          end

          if not count then
            dbot.warn("Failed to migrate " .. fileInfo.desc .. ": " .. (migrateErr or "unknown"))
            table.insert(results, { desc = fileInfo.desc, status = "FAILED", detail = migrateErr })
            migrationFailed = true
            failureMsg = migrateErr
            return DRL_RET_INTERNAL_ERROR
          else
            table.insert(results, { desc = fileInfo.desc, status = "OK", count = count })
          end
        end -- if data
      end -- if exists
    end -- for

    -- Validate counts
    local validationPassed = true
    for _, r in ipairs(results) do
      if r.status == "OK" and r.count then
        local tableName, expected

        if r.desc == "Items" then
          tableName = "items"
          expected = r.count
        elseif r.desc == "Priorities" then
          tableName = "priorities"
          expected = r.count
        elseif r.desc == "Sets" then
          tableName = "sets"
          expected = r.count
        elseif r.desc == "Snapshots" then
          tableName = "snapshots"
          expected = r.count
        elseif r.desc == "Consumables" then
          tableName = "consumables"
          expected = r.count
        elseif r.desc == "Custom cache" then
          tableName = "cache_custom"
          expected = r.count
        elseif r.desc == "Frequent cache" then
          tableName = "cache_frequent"
          expected = r.count
        elseif r.desc == "Recent cache" then
          tableName = "cache_recent"
          expected = r.count
        elseif r.desc == "Spell bonuses" then
          -- Direct validation against stat_bonuses (equip bonuses no longer migrated
          -- post-v3.0097, so the row count matches the spell migration count directly)
          tableName = "stat_bonuses"
          expected = r.count
        elseif r.desc == "Config" then
          tableName = nil  -- Config uses INSERT OR REPLACE, count may not match exactly
        end

        if tableName then
          local actual, ok = validateCount(tableName, expected)
          if not ok then
            dbot.warn(string.format("Validation failed for %s: expected %d rows, found %d",
                      r.desc, expected, actual))
            r.status = "MISMATCH"
            r.actual = actual
            validationPassed = false
          end
        end
      end
    end

    if not validationPassed then
      migrationFailed = true
      failureMsg = "Count validation failed"
      return DRL_RET_INTERNAL_ERROR
    end

    return DRL_RET_SUCCESS
  end)

  -- Display results
  dbot.print("")
  if retval == DRL_RET_SUCCESS then
    if anyLoadFailed then
      dbot.print("@Y  Migration completed with failures.@w")
      dbot.print("@W  One or more state files could not be read. The categories marked FAILED")
      dbot.print("@W  below were skipped; everything else was imported. Details were written to:")
      dbot.print("@C    " .. getErrorLogPath() .. "@w")
      dbot.print("@W  Restore your previous data with: @Gdinv backup restore pre-migrate@w\n")
    else
      dbot.print("@G  Migration completed successfully!@w\n")
    end
  else
    dbot.print("@R  Migration failed: " .. (failureMsg or "unknown error") .. "@w")
    dbot.print("@R  The migration was rolled back. Your database is now empty.@w")
    dbot.print("@W  Restore your previous data with: @Gdinv backup restore pre-migrate@w\n")
  end

  -- Results table
  dbot.print("@C  Migration Results@w")
  dbot.print("@W  " .. string.rep("-", 45) .. "@w")

  for _, r in ipairs(results) do
    local line
    if r.status == "OK" then
      line = string.format("@W  %-16s @G%5d migrated@w", r.desc, r.count)
    elseif r.status == "MISMATCH" then
      line = string.format("@W  %-16s @R%5d expected, %d found@w", r.desc, r.count, r.actual)
    else
      line = string.format("@W  %-16s @RFAILED@w: %s", r.desc, r.detail or "unknown")
    end
    dbot.print(line)
  end

  dbot.print("")

  if retval == DRL_RET_SUCCESS then
    dbot.info("Reloading plugin to apply migrated data...")
    -- Re-init in-process WITHOUT saving the current state.  The migration wrote
    -- straight to SQLite, so the in-memory tables are still pre-migrate; a full
    -- dbot.reload() would let the unload-time OnPluginSaveState flush that stale
    -- state back over the freshly-migrated database via each module's DELETE-
    -- and-reinsert save(), wiping everything that was just imported.  inv.reload
    -- with drlDoNotSaveState skips the save and reloads from disk instead -- the
    -- same path "dinv backup restore" uses after swapping the database file out-
    -- of-band.
    local reloadRetval = inv.reload(drlDoNotSaveState)
    if (reloadRetval ~= DRL_RET_SUCCESS) then
      dbot.warn("inv.migrate.execute: Failed to reload plugin after migration: " ..
                dbot.retval.getString(reloadRetval))
    end -- if
  end

  return retval
end
